### ISSUE TITLE
ATTENTION! DevGPT is dubious and provides no contact options when problems occur

### ISSUE THREAD

**Issue by CodingDanny** [devgpt-labs/devgpt#270] opened 2024-02-18 20:15 UTC
I wanted to start a 30 day free trial, but somehow they charged me after only 7 days. I tried to contact them, but the provided mail address "support@feb.co.uk" does not exist. I tried to contact DevGPT under "support@devgpt.com", a second mail that can be found on the website, but there hasn't been any answer so far. 
But it got worse: I cancelled the abo, but they charged me again (!) a couple of days later and when I checked my account, there was another abo (same DevGPT account as before) with a 30 day free trial that has started at the same say as the first one mentioned above (with the wrong test trial). This second abo was not visible before, so I couldn't have cancelled it, but the test trial has ended, so this is why they wrongly charged me again.
<img width="310" alt="Rechnungshistorie1" src="https://github.com/devgpt-labs/devgpt/assets/93346331/0419b772-faed-40f3-bf8e-f1666ae10ee7">
![Rechnungshistorie2](https://github.com/devgpt-labs/devgpt/assets/93346331/dcb23bd0-f513-4e6c-8d0a-f5840e6aa8d5)

**Comment by den-vasyliev** [comment] 2024-03-05 22:38
I sent dispute to stripe platform https://support.stripe.com/contact/email

**Comment by CodingDanny** [comment] 2024-03-05 22:54
> I sent dispute to stripe platform https://support.stripe.com/contact/email

I also complained at Stripe and I think it is good when more people do so. I also arranged a charge back via my credit card company, so I have my money back and so far, there hasn't been any reaction (that seems the way they handle things)..

**Comment by ash-lewis** [comment] 2024-03-05 23:01
Closing this as it's a duplicate of your other issue, thanks again for raising though, please just send an email to support with the email address you created your DevGPT account on and you will not be billed further, we'll also issue refunds if you were unhappy with the service. This sometimes happens if duplicate accounts were created during sign up.

**Closed as completed by ash-lewis** 2024-03-05 23:01 UTC

**Comment by CodingDanny** [comment] 2024-03-05 23:05
> Closing this as it's a duplicate of your other issue, thanks again for raising though, please just send an email to support with the email address you created your DevGPT account on and you will not be billed further, we'll also issue refunds if you were unhappy with the service. This sometimes happens if duplicate accounts were created during sign up.

I have written multiple mails to support@devgpt.com over the last months without any answer.
